services:
  api:
    container_name: TEST API
    environment: 
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=librarypass
      - PGDATABASE=library_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: debug_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=library_test
      - POSTGRES_PASSWORD=librarypass
volumes:
  test_db:
networks: 
  default:
    name: debug_test
